### ISSUE TITLE
Just to be sure...

### ISSUE THREAD

**Issue by perak** [Strilanc/Quirk#372]
Hi @Strilanc 

Maybe I don't understand something (or can possibly be a bug) :

Is it normal behavior that controlling qubit changes depending on value of controlled one?

Example:

When Z^½ gate on qubit 1 is controlled by qubit 0, ϕ of qubit 0 is -45° :
http://algassert.com/quirk#circuit={"cols":[["X^½","X^½"],["•","Z^½"]]}

<img width="686" alt="screen shot 2017-08-12 at 11 35 35 pm" src="https://user-images.githubusercontent.com/5630814/29244496-5d176464-7fb9-11e7-9fcc-7bffc5a69ed4.png">

Now if I remove control (and leave Z^½ on qubit 1 uncontrolled),  ϕ of qubit 0 is -90° :
http://algassert.com/quirk#circuit={"cols":[["X^½","X^½"],[1,"Z^½"]]}

<img width="696" alt="screen shot 2017-08-12 at 11 35 17 pm" src="https://user-images.githubusercontent.com/5630814/29244498-6bc23138-7fb9-11e7-8ab5-e3deefa471b5.png">

I just want to know is it normal behavior or is a bug?

Thanks! :)

**Comment by Strilanc** [comment]
Thanks for the report.

Yes, that's normal behavior. In fact it's useful! It's an example of what people call ["phase kickback"](https://www.quora.com/What-is-phase-kickback-and-how-does-it-occur).

A practical example of phase kickback being useful is in the surface code's Z^(1/2) gate contruction. The surface code can't do Z^(1/2) gates natively. [But it can apply CNOTs and Hadamards involving an ancilla, in a way that causes a phase kickback equivalent to a Z^(1/2) gate](https://arxiv.org/abs/1708.00054).

A more dramatic example is what happens if you surround a CNOT with Hadamards: you end up flipping the _control_ if the _target_ is on. You might find [Thinking of Operations as Controls](http://algassert.com/post/1706) useful to read.

**Comment by perak** [comment]
Hi @Strilanc thank you very much for detailed explanation! 👍
