### ISSUE TITLE
The shown green filling of off-diagonal density matrix elements is incorrect

### ISSUE THREAD

**Issue by lucainnocenti** [Strilanc/Quirk#397]
Consider the density matrix displayed on a line after a single H gate:
![screenshot 2017-12-13 11 45 31](https://user-images.githubusercontent.com/10957113/33937379-2a1b1eaa-dffb-11e7-914b-cb57c62a7b85.png)

I find the above confusing. The density matrix after the H gate should have 1/2 in all elements, which is what is correctly shown on the tooltip. However, the green filling of the off-diagonal elements would lead to think that the off-diagonal elements have zero magnitude.

Is this intended? Am I missing something?

**Comment by Strilanc** [comment]
This is intended. It's a way of making the off-diagonal elements look different from the diagonal elements, since only the on-diagonal elements correspond to probabilities.

It also makes the density matrix displays  look different from the amplitude displays and how the custom-matrix-gates are drawn when they have no symbol. Though that's really not as important since the colors differ already.

Originally, the on-diagonal elements were *just* the green rectangle filling. I didn't include the circle indicator because the phase was always 0. But the circles stand out more (especially for small values where the logarithmic length of the line dominates), so for large displays it was impossible to even see the diagonal.

I'm definitely conflicted over whether I want the boxes to be consistent with other complex number displays or whether I want to keep highlighting the diagonal.

**Comment by lucainnocenti** [comment]
I'm fine with the diagonal elements still showing the clocks, but in my opinion not showing the magnitudes of off-diagonal elements is confusing. It basically means that you cannot see the correlations without hovering with the mouse over the single elements, and the correlations are important in many situations.

**Comment by Strilanc** [comment]
Closing as WONTFIX, because I do visually prefer the existing mechanism.
