### ISSUE TITLE
Spurious disabling of interleave/deinterleave that doesn't affect classical bit

### ISSUE THREAD

**Issue by NoLongerBreathedIn** [Strilanc/Quirk#403]
As far as I can tell, there is no reason to disable an interleave circuit because the first or last bits are classical. Sample minimal example:
http://algassert.com/quirk#circuit={"cols":[["Measure"],["split4",1,1,1,"•"]]}

**Comment by Strilanc** [comment]
Ah, good point. When a permutation has sets of qubits that aren't mixed into the others, it should be okay to have each set be measured or not measured.

**Comment by Strilanc** [comment]
This is fixed by https://github.com/Strilanc/Quirk/pull/404/commits/a9205f04ba3a3f2c232133fd23a95b041b6fb97d in #404 and will appear in the next release.

I was surprised that there were some non-trivial permutation subgroups:

![image](https://user-images.githubusercontent.com/79941/41140577-b0d5b06e-6ac4-11e8-907b-5dcbb6ef13ff.png)
