### ISSUE TITLE
Drag qubit lines

### ISSUE THREAD

**Issue by afowler** [Strilanc/Quirk#406]
Wouldn't it be awesome to be able to rearrange circuits by dragging qubit lines up and down? Suggest making the initial |0> a draggable object.

**Comment by Strilanc** [comment]
One of the tricky things here is what should happen to multiqubit operations.

![image](https://user-images.githubusercontent.com/79941/42481091-6d057786-8395-11e8-9e2a-80ea1fd33218.png)

Here's what I think the rules would be:

- The multi-qubit operation is only associated with its first qubit. As far as all other qubits it touches are concerned, it doesn't exist. So, if you drag the last qubit of a QFT downward, the QFT stays behind.
- When you drag a qubit with a single-qubit gate on it into the middle of a multi-qubit operation, the single-qubit gate gets displaced into a new column to the right.
- When you drag a qubit with a control on it into the middle of a multi-qubit operation, the operation is disabled (by the existing "control inside gate" check) until you release, at which point the control is pushed into a new column to the right.
- When a multi-qubit operation is pushed downward so far that it would push past the 16 qubit limit (either due to its first qubit being moved or a qubit being moved from inside it to above it), the operation will shrink in size to accomodate. If there is not a small enough version of the operation to fit, it is placed as low as possible. If this causes it to overlap with existing operations, it is pushed rightward into a new column.

**Comment by afowler** [comment]
My thought is the circuit after rearrange should be absolutely functionally
identical. If qubits are part of multi-qubit operations that don't support
this, initially don't allow the drag. Maybe later make all connected qubits
move as a block.

**Comment by Strilanc** [comment]
Most of the other dragging moves don't go out of their way to preserve functionality, so it would be unusual for the wire drag to be uniquely obsessed with it. Preventing the drag if it doesn't preserve functionality seems particularly perverse, because I imagine in most use cases the wire drag will save work by *almost* doing what you want (so you only have to do the tweaks instead of the whole task).

I can definitely make the drag functionally neutral by judiciously introducing/cancelling swap/rotation gates. I would need to think carefully about this, so that reordering wires couldn't cause the swaps to grow without bound and wouldn't take away swap gates that the user actually wanted to keep.

**Comment by afowler** [comment]
IMHO, when I want to reorder qubits, it's purely for visual purposes, so
keeping functionality and not having to check it's preserved would be most
important. A column reorder is just different in my mind...

**Comment by mhlr** [comment]
Semantics preserving qubit reordering would be excellent.

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Quirk/pull/404/commits/7b1b065a5edfc3e9f4bf4972f66e744aa5cb15fc , which does the simplest possible thing (gates associated with their top wire). Will be in next release.

**Comment by afowler** [comment]
Yay!
