### ISSUE TITLE
Use Quirk as Quantum Circuit deawing tool without simulation

### ISSUE THREAD

**Issue by AbdallaEssamAli** [Strilanc/Quirk#412]
I want to be able to draw a big quantum circuit with more than 32 qubits, without the need for the simulation. So I want to know how to be able to disable simulation while being able to draw circuits.

**Comment by Strilanc** [comment]
This is not a feature I am going to support in the master version of Cirq, but the `big-circuit-support-no-sim` branch has this feature implemented.

In order to use Quirk in this way, you will have to clone the repo, checkout that branch, run the build (see the README), and then open the produced html file. Once you do, you should be able to make arbitrarily large circuits and the simulation will turn off after 16 qubits.

Another useful feature limited to that particular branch is that if you hold the 'X' key while clicking the mouse, an X gate will appear in the circuit where you clicked (so you don't have to go all the way to the toolbox). Other keys this works for are Y, Z, H, S, T, and C (control).

**Comment by AbdallaEssamAli** [comment]
Thank you that works great. 
But can you add another shortcut for the anti-control with A key for example.

Is there any detailed code documentation to help other who want to add other features to Quirk?

**Comment by Strilanc** [comment]
Unfortunately, there isn't. But I can answer specific questions you open in the issues.

If you want to add more gate-keyboard commands, search `'X', Gates` in [this commit](https://github.com/Strilanc/Quirk/commit/5992cf3eedf692eaac11eb6bd4d01a40433b3cb4).

**Comment by Strilanc** [comment]
Closing as WONTFIX (but it is on that alternate branch)
