### ISSUE TITLE
Write wavefunction amplitudes to file

### ISSUE THREAD

**Issue by zerodynamics** [Strilanc/Quirk#413]
I often want to use the output in another simulation or just parse through to look for specific states.

**Comment by Strilanc** [comment]
I could add a "copy current output to clipboard" section to the export menu.

**Comment by zerodynamics** [comment]
That would be great.  Perhaps as state_string:amplitude_value pairs ?

**Comment by AbdallaEssamAli** [comment]
Is there any news about this feature. 
Or even some guidance about implementing it. @Strilanc

**Comment by Strilanc** [comment]
I haven't worked on this feature (or anything else Quirk-related) recently.

To implement this feature, you would try to mimic the way the "json of circuit" export box works, except accounting for the caveat that producing the string describing the wavefunction is significantly more expensive and so needs to be a) throttled and b) not happening unless the export window is open.

The json export is done using functional reactive programming, in order to avoid polluting the main loop with a bunch of "and then remember to update X and Y and Z" UI boilerplate. There is an Observable tracking the latest committed circuit, and this observable is given to the init function of the json export file so that it can subscribe an observer that updates the text box. To make the state export work, you will need to modify the main file to track the latest simulated state using an observable value, and pass that observable into an init method that combines it with an "is the export window showing observable". You would then apply the function (I don't quite recall the name offhand) that drops redundant events with the same items, apply a throttle, and then apply a map that took the simulation state and returned the state string (or else None if the simulation state had been replaced by None due to the export window now showing).

If you run into trouble, just ask here.

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Quirk/pull/404/commits/f09cd086022af4837d32babcd55bb0b85813b87c . Will be in next release.
