### ISSUE TITLE
Shor's algorithm demo

### ISSUE THREAD

**Issue by algonte** [Strilanc/Quirk#418]
In the Shor's algorithm demo QFT+ (daga) is used instead of QFT, but what is obtain with the meassurement is a multiple of the frequency of the corresponding measured value of (a exp x) mod N, so I guess the QFT is what has to be applied. But both QFT+ and QFT give the same results (¿?)

**Comment by Strilanc** [comment]
If you apply the QFT instead of the inverse QFT, the amplitude that would have been at state k will be at state -(k % 2^n) instead where n is the number of qubits in the register you applied the QFT to. You're correct that, because the peaks in the output happen to be evenly spaced, with a period that is approximately a divisor of 2^n, it doesn't particularly matter which one you use.

The reason the inverse QFT is used instead of the QFT is because Shor's algorithm is a specific instantiation of phase estimation, and in phase estimation the convention is to use the inverse QFT because then you don't have to post-process the results to undo the negation (though the post-processing is trivial).

**Comment by Strilanc** [comment]
Run a fourier transform twice, and pay careful attention to what operation this is performing; what inputs become what outputs.
