### ISSUE TITLE
Get circuit matrix

### ISSUE THREAD

**Issue by alxhotel** [Strilanc/Quirk#424]
Is there a way to get the matrix of the whole circuit?

Or do you know of an online tool to easily get it?

Thanks

**Comment by Strilanc** [comment]
You can use the state channel duality, and the lucky accident that the output state display is arranged into a square, in order to get a view of the matrix. Just do the following:

1) Create k EPR pairs, split between the top and bottom half of the circuit.
2) Apply your operation to the top half (or bottom half).
3) Look at the output display. It is showing the matrix (or transpose of the matrix) of the operation you applied (times a scaling factor).

For example, in this image I use QFT and Addition gates to prepare the EPR pairs. Then I do an increment and a phase gradient operation. The output state display is showing a state that is proportional to the matrix of the increment + phase gradient circuit:

![image](https://user-images.githubusercontent.com/79941/54561991-42b1c200-4983-11e9-8211-453faf4549c4.png)

See also this blog post: https://algassert.com/quantum/2015/04/25/Entangled-States-are-like-Unitary-Matrices.html

**Comment by stellarpower** [comment]
For us, it would have been really useful to get a matrix representing just one column left-right of the circuit, i.e. the result of the tensor product of all the gates for that stage in time evolution.

**Comment by Strilanc** [comment]
@stellarpower Apply the above trick before your circuit starts and place an amplitude display after the first layer of your circuit. The amplitude display is now showing you the matrix of the first layer of your circuit.
