### ISSUE TITLE
Bloch sphere in skewed "pseudo 3d"?

### ISSUE THREAD

**Issue by beccare** [Strilanc/Quirk#435]
Is it just me who cannot understand how the y-z plane stays in the drawing plane, while the x-y- and the z-x-planes are slanted for better view?

I mean, this is how the bloch sphere and spheres in physics is always drawn, indeed, but nobody seems to mention that this way, the Bloch-vector is always skewed... Or did I miss a disclaimer somewhere?

It's not Quirk's fault but imho, perspective actually works like this: https://www.jasondavies.com/maps/rotate/

Never mind, Quirk is a supreme tool ! I just happen to stumble upon that question in this context for the first time,  and I needed to share it for my own sanity ;-)

**Comment by Strilanc** [comment]
It's just because I wanted to keep things simple. The representation cheats in many ways, such as how the occlusion of the stick connecting the center to the ball is just an alpha transition across z=0 instead of any kind of z test (well, x test, since physicists for some reason want the X axis to not go from left to right).

If you would like to improve the look of the bloch sphere display, feel free to give it a try. Take the bounding box of the sphere, the bloch vector, and use the available canvas commands to draw something nice.

**Comment by Strilanc** [comment]
I'm going to close this issue as "won't fix". Not because I don't want it to be done but because I know that I personally won't be investing the time to get it done.
