### ISSUE TITLE
The implementation of Input Gate

### ISSUE THREAD

**Issue by weiwenjiang** [Strilanc/Quirk#450]
https://algassert.com/quirk#circuit={%22cols%22:[[%22Y%22],[%22inputA1%22,%22Y^(A/2^n)%22],[%22Y^(A/2^n)%22,%22inputA1%22]]}

Can you have comments on how such an input gate (as used in the above link) to be implemented? Such as that in Qiskit?

Thanks!

**Comment by Strilanc** [comment]
The IBM chips only allow CNOTs in one direction right?

Start from the circuit:

![image](https://user-images.githubusercontent.com/79941/72081305-a15e7880-32d4-11ea-9ef4-7eeb419a51a1.png)

Rewrite into controlled sqrt Ys:

![image](https://user-images.githubusercontent.com/79941/72081291-999ed400-32d4-11ea-8148-7e364699d697.png)

Change basis so that the controlled operations are Z type:

![image](https://user-images.githubusercontent.com/79941/72081397-cd79f980-32d4-11ea-8bca-85af46878cf2.png)

Expand each CS into two CNOTs with various T gates:

![image](https://user-images.githubusercontent.com/79941/72081490-f601f380-32d4-11ea-8ef4-76b86c3cc672.png)

Rearrange operations, changing basis of CNOTs if necessary, so that two of the CNOTs are next to each other:

![image](https://user-images.githubusercontent.com/79941/72081546-0e720e00-32d5-11ea-8dab-7bb15c55273c.png)

When two adjacent two qubit operations have a common target type (or control type) on the same qubit, you can merge them:

![image](https://user-images.githubusercontent.com/79941/72081567-1cc02a00-32d5-11ea-9815-dea05054054d.png)

Change basis so that all two qubit operations are CNOTs in the same direction:

![image](https://user-images.githubusercontent.com/79941/72081646-3b262580-32d5-11ea-9e8a-78718f0ef67e.png)

Alternatively, you can just do this:

```
import cirq
a, b = cirq.LineQubit.range(2)
c = cirq.Circuit(
    cirq.Y(a),
    cirq.Y(b).controlled_by(a)**0.5,
    cirq.Y(a).controlled_by(b)**0.5)
c2 = cirq.google.optimized_for_xmon(c)
```

and get a decomposition using two CZs (easily changed into two CNOTs). The intermediate single qubit gates are not nice, though:

```
0: ───PhasedX(0.25)^0.944────@───PhasedX(0.75)^0.25─────@───PhasedX(-0.195)^0.255────Z^0.773───
                             │                          │
1: ───PhasedX(0.578)^0.255───@───PhasedX(-0.477)^0.25───@───PhasedX(0.0231)^0.0556───Z^0.227───
```
